// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session-scoped slow mode control. This RPC never starts a turn.
 */
export type ThreadSlowModeParams = { threadId: string,
/**
 * `on`, `off`, or `status`.
 */
action: string, };
