// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSlowModeResponse = { enabled: boolean, model: string | null, fastMode: boolean | null, primaryUsedPercent: number | null, primaryResetsInSecs: bigint | null, secondaryUsedPercent: number | null, secondaryResetsInSecs: bigint | null, estimatedRequestCostPercent: number | null, nextEligibleInSecs: bigint | null, queuedModelRequests: bigint, preservingSecondary: boolean, note: string | null, };
